<?php

declare(strict_types=1);

namespace Axleus\DevTools\Debug;

use Tracy\Debugger;
use Tracy\Dumper;
use Mezzio\Router\RouteCollectorInterface;

if(! $data instanceof RouteCollectorInterface) {
    return;
}

Dumper::renderAssets();
Debugger::$maxLength = 250;
?>
<div class="tracy-inner tracy-QueryPanel">
    <div class="tracy-inner-container">
        <?php Dumper::dump($data->getRoutes());?>
    </div>
</div>