<?php

declare(strict_types=1);

namespace Webware\Traccio\Debug;

use Tracy\Debugger;
use Tracy\Dumper;
use Mezzio\Router\RouteCollectorInterface;

if(! $data instanceof RouteCollectorInterface) {
    return;
}

?>
<div class="tracy-inner tracy-QueryPanel">
    <div class="tracy-inner-container">
        <?= Dumper::toHtml($data->getRoutes(), [
            Dumper::DEPTH => Debugger::$maxDepth,
            Dumper::ITEMS => Debugger::$maxItems,
            Dumper::TRUNCATE => Debugger::$maxLength,
            Dumper::LOCATION => Debugger::$showLocation ?: Dumper::LOCATION_CLASS | Dumper::LOCATION_SOURCE,
            Dumper::KEYS_TO_HIDE => Debugger::$keysToHide,
            Dumper::THEME => Debugger::$dumpTheme,
            Dumper::LAZY => true,
        ]) ?>
    </div>
</div>