<?php

declare(strict_types=1);

namespace Webware\Traccio\Debug;

use Mezzio\Router\Route;
use Mezzio\Router\RouteCollectorInterface;
use Tracy\Debugger;
use Tracy\Dumper;

if (! $data instanceof RouteCollectorInterface) {
    return;
}

$routes = array_reduce(
    $data->getRoutes(),
    static fn(array $carry, Route $route): array => $carry + [$route->getName() => $route],
    []
);
ksort($routes);

?>
<div class="tracy-inner tracy-RoutesPanel">
    <div class="tracy-inner-container">
        <?= Dumper::toHtml($routes, [
            Dumper::DEPTH => Debugger::$maxDepth,
            Dumper::ITEMS => Debugger::$maxItems,
            Dumper::TRUNCATE => Debugger::$maxLength,
            Dumper::LOCATION => Debugger::$showLocation ?: Dumper::LOCATION_CLASS | Dumper::LOCATION_SOURCE,
            Dumper::KEYS_TO_HIDE => Debugger::$keysToHide,
            Dumper::THEME => Debugger::$dumpTheme,
            Dumper::LAZY => true,
        ]) ?>
    </div>
</div>